# versão especificada de acordo com a matriz de versão do Docker
version: '3.8'

# Especifica quais containers serão "rodados"
services:

  db:         #container de banco de dados
    image: mysql:5.7
    restart: always
    networks:
      - stack_web
    
    labels:
      com.example.description: "Financial transaction network"
  
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql

  wordpress:       #container wordpress
    depends_on:    #especifica uma dependência para subir o serviço; nesse caso, o banco de dados
      - db
    image: wordpress:latest
    networks:
      - stack_web
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
# Volumes referencidos na criação dos containers
volumes:
  db:
  wordpress:
# Especificação da rede a ser usada
networks:
  stack_web:
